"""Weight now nullable

Revision ID: 0152fb6f369a
Revises: 55f4d3b54ec9
Create Date: 2022-11-11 14:00:06.028289

"""
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0152fb6f369a'
down_revision = '55f4d3b54ec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'weight',
                    existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    # ### end Alembic commands ###
