"""Products and Users now have boolean attribute 'active'

Revision ID: 25b560b05038
Revises: 5e8827f4aa60
Create Date: 2022-12-06 00:02:35.049258

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '25b560b05038'
down_revision = '5e8827f4aa60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE products SET active=true;")
    op.execute("UPDATE users SET active=true;")
    op.alter_column('products', 'active', nullable=False)
    op.alter_column('users', 'active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    op.drop_column('products', 'active')
    # ### end Alembic commands ###
