"""Initial

Revision ID: 55f4d3b54ec9
Revises: 
Create Date: 2022-11-10 22:09:39.061819

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '55f4d3b54ec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('product_price_index', 'products', ['price'], unique=False)
    op.create_index('product_title_index', 'products', ['title'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), autoincrement=True,
                              nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('second_name', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('user_username_index', 'users', ['username'], unique=False)
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_index('user_username_index', table_name='users')
    op.drop_table('users')
    op.drop_index('product_title_index', table_name='products')
    op.drop_index('product_price_index', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
