"""User's second name and username are nullable now + id now is telegram id

Revision ID: 5e8827f4aa60
Revises: 0152fb6f369a
Create Date: 2022-11-11 16:15:22.043773

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5e8827f4aa60'
down_revision = '0152fb6f369a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'second_name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'second_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
