"""Order info

Revision ID: 90cc19960065
Revises: 25b560b05038
Create Date: 2023-03-24 18:31:58.145301

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90cc19960065'
down_revision = '25b560b05038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('country_code', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('city', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('street_line1', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('street_line2', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('post_code', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('total_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_amount')
    op.drop_column('orders', 'post_code')
    op.drop_column('orders', 'street_line1')
    op.drop_column('orders', 'city')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'country_code')
    op.drop_column('orders', 'phone_number')
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
