"""Order date info

Revision ID: d978178c2f10
Revises: 90cc19960065
Create Date: 2023-04-11 20:30:03.072613

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd978178c2f10'
down_revision = '90cc19960065'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders',
                  sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ordered_at')
    # ### end Alembic commands ###
